### ISSUE TITLE
`pyk` cannot find llvm backend bindings correctly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#119]
~Blocked on: https://github.com/runtimeverification/llvm-backend/issues/611~

---

On my system, for some reason it cannot find the LLVM backend bindings:

![image](https://user-images.githubusercontent.com/12721972/204321559-b9c43b51-d9af-4c1d-93c6-75a35343f4f1.png)

It appears it's a Python3.9 vs Python3.10 issue?

![image (1)](https://user-images.githubusercontent.com/12721972/204322037-67e9bc03-b4b4-45c3-9a83-953ab821adf2.png)

**Comment by Baltoli** [comment]
Taking a look!

**Comment by Baltoli** [comment]
The KLLVM bindings, when built using Nix, will always be Python 3.9: https://github.com/runtimeverification/llvm-backend/blob/3620054f1542481fbb6f04d146bf0e91eaac676b/nix/overlay.nix#L50-L56

**Comment by tothtamas28** [comment]
@Baltoli is it safe to weaken the binding's Python tag to `py3`? If not, I guess we'll have to compile the binding during runtime (as we do for the runtime bindings).

**Comment by Baltoli** [comment]
I think that's safe @tothtamas28; I can't think of anything that requires a particular minor version. If I'm wrong and it breaks I'll revisit the runtime compilation approach

**Comment by ehildenb** [comment]
This appears to no longer be a problem on my system, is it resolved then?

**Comment by Baltoli** [comment]
I've not changed anything - @tothtamas28 ?

**Comment by tothtamas28** [comment]
> I've not changed anything - @tothtamas28 ?

Related to the issue I haven't. But I've ported these tests from `unittest` to `pytest`, so this might explain why the issue is not triggered. Running `test_implies` should not touch the module where the issue is, and maybe this is handled in a more reasonable way now.

@ehildenb, does this trigger the error?

```
make test-integration TEST_ARGS='-k test_parser'
```

**Comment by ehildenb** [comment]
It turns out that it's still a problem, yes. Not sure why it stopped manifesting for a bit, but updating pyk resulted in it coming back.

**Comment by tothtamas28** [comment]
Until https://github.com/runtimeverification/llvm-backend/issues/611 is fixed (and the corresponding changes are made in `pyk`), a workaround is to point Poetry to the Python binary with the right version (in this case, the one that `nix` installed):

```
$ poetry env use path/to/python3.9
```
