### ISSUE TITLE
[ksimplify] - Tool for simplifying matching logic patterns

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#12]
Blocked on: https://github.com/runtimeverification/haskell-backend/issues/3298

- `ksimplify [<kast-arg>*] <pattern-file>`: Parse in `<pattern-file>` (containing potential symbolic variables), simplify it, and print the result. All the same sort/parsing options handled by `kast` are handled here.

One approach to implementing these features is document here: https://docs.google.com/drawings/d/1XIjyPCjB6GBEDCw1S_0ik-kvQPrTctqYINOnVI1Ww_I/edit

- [x] Haskell backend implements `kore-simplify`: https://github.com/runtimeverification/haskell-backend/issues/3011
- [ ] Frontend implements new `ksimplify` command, which has basically the same interface as `kast`, but invokes `kore-simplify` between parsing and unparsing.

**Comment by radumereuta** [comment]
Ana: We should remove `kore-simplify`, pyk should implement a wrapper over the simplify endpoint provided by the `kore-rpc` server. The summarizer should provide the backend with simplification tests to help us reimplement the simplifier component.

**Comment by ehildenb** [comment]
Reopen if needed still. We mostly use the RPC server directly anymore.
