### ISSUE TITLE
Factor out Kast <-> Kore conversions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#121]
We currently have `KPrint.kast_to_kore` and `KPrint.kore_to_kast`. These methods have to be in `KPrint` because they require a `KDefinition`, and fall back to binary `kast` when the methods `KPrint._kast_to_kore` and `KPrint._kore_to_kast` fail to do the conversions.

Now that `KPrint._kast_to_kore` and `KPrint._kore_to_kast` have matured, we should try to factor them out of `KPrint` class. In particular:

- [ ] (Optional) Split [kore.syntax](https://github.com/runtimeverification/pyk/blob/master/src/pyk/kore/syntax.py) into Inner and Outer similar to how Kast is (reduce file size, make it easier to do targeted imports).
- [x] Add a `injections` table to [`Definition`](https://github.com/runtimeverification/pyk/blob/master/src/pyk/kore/syntax.py#L1899) similar to the subsorts table in [`KDefinition`](https://github.com/runtimeverification/pyk/blob/master/src/pyk/kast/outer.py#L839). It should scan the `Definition` and find Injection productions and store them as a dictionary with the key being the supersort of the injection and the values being the various subsorts it maps to. #126 
- [x] Implement `Definition.add_sort_injections`, which traverses a given Kore term and adds sort injections where needed (or fails with value error if no injections exist for the given sort pair don't exist). This should basically replace [`KPrint._add_sort_injection`](https://github.com/runtimeverification/pyk/blob/master/src/pyk/ktool/kprint.py#L552). May want to implement `bottom_up` on `Pattern` to facilitate this. https://github.com/runtimeverification/pyk/pull/134
- [ ] Add to each `KInner` subclass a method `KInner.kore`, which implements the logic of [`KPrint._kast_to_kore`](https://github.com/runtimeverification/pyk/blob/master/src/pyk/ktool/kprint.py#L403) directly, except it doesn't add any sort injections.
- [ ] Implement a new method `KInner.from_kore`, which reproduces [`KPrint._kore_to_kast`](https://github.com/runtimeverification/pyk/blob/master/src/pyk/ktool/kprint.py#L292).
- [ ] Re-implement `KPrint.{kast_to_kore,kore_to_kast}` in terms of these new methods, with the difference being taht we use `KInner.kore` for producing the kore, and then do a second traversal to add the injections.

**Comment by tothtamas28** [comment]
`KInner.from_kore` and `KInner.to_kore` introduce coupling between the `kore` and `kast` modules, which is undesirable. The other mandatory items are done.
