### ISSUE TITLE
Function `run_process` should be propagating stderr

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#14]
Currently, when we make subprocess calls, the stderr is silently dropped, which leads to warnings printed by K being ignored.

We should be propagating it instead: https://github.com/runtimeverification/k/pull/2763#discussion_r937034967

**Comment by radumereuta** [comment]
We have a similar issue in the front-end: https://github.com/runtimeverification/k/issues/2731
We should maintain the same behavior between our tools so these two issues should be handled in a similar way.
