### ISSUE TITLE
Clean up token encoding

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#145]
Blocked on: #140
Blocked on: https://github.com/runtimeverification/k/issues/3082

Once the question of how to store tokens is settled, implement the solution agreed upon. If the decision is
1 "Store as parsed": simplifies `KToken.from_dict` and `KToken.to_dict`.
2. "Store decoded": simplifies `KPrint.kast_to_kore` and `KPrint.kore_to_kast`

Right now both classes contain custom code for `String` and `Bytes`.

**Comment by ehildenb** [comment]
I definitely prefer `kast_to_kore` and `kore_to_kast` to be simpler if possible, because those are actually semantic functions, and not just reading/writing storage formats.
