### ISSUE TITLE
`KcfgViewer` should enable navigation using keystrokes

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#148]
In `KLab` the user can step through the chains of nodes at whatever granularity they are stored using "forward" and "backward" (`n` for next, `p` for previous). Modifiers make the jumps bigger (`Shift-n` means jump all the way forward to next branch, `Shift-p` means jump backward all the way to previous branch, for example).

(Matching the same keystrokes doesn't matter, but the navigation concept itself.)

**Comment by ehildenb** [comment]
We are using mouse-clikc navigation now.
