### ISSUE TITLE
Allow return code checks on all K tools

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/pyk#164]
In #160, we add a feature to `KRun` that allows the expected return code to be checked (rather than just failing if it's non-zero). We should make this change generically in the `cli_utils` module.

**Comment by ehildenb** [comment]
It appears that `run_process` checks return codes: https://github.com/runtimeverification/pyk/blob/b46fdfbbf87bbd731f7fa00afca902ab2f86c705/src/pyk/utils.py#L373

Probably each of the uses that shows up here we should consider threading through the `check: bool = False` argument to `run_process`.

**Comment by ehildenb** [comment]
I believe this is done now.
