### ISSUE TITLE
Upstream `match_ac` function

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/pyk#166]
The K summarizer contains a limited AC matching function that does bipartite matching over a list of clauses and terms to produce the set of potential matches. We should upstream this function to Pyk and add test cases.

https://github.com/runtimeverification/ksummarize/blob/6f8b5858338024087c64d59a78ab448db96ede03/ksummarize/src/ksummarize/util.py#L332

**Comment by ehildenb** [comment]
No one else has called for this, so we can close.
