### ISSUE TITLE
Argument list too long: 'kast' when using large configurations

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/pyk#265]
To reproduce:

1. Checkout the `pyk-issue` branch here in a fresh client: https://github.com/runtimeverification/wasm-semantics/tree/pyk-issue
2. In scripts/compress_bytes/compress_bytes.py change ROOT to point to your client.
3. Run:
```
make build-haskell
cd scripts
poetry install
poetry shell
python3 -m compress_bytes.compress_bytes
```

**Comment by ehildenb** [comment]
I believe this is addressed with: https://github.com/runtimeverification/pyk/pull/266.

Re-open if not!
