### ISSUE TITLE
Performance improvements for KORE

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#267]
https://github.com/runtimeverification/evm-semantics/pull/1631#issuecomment-1470298268

* [x] Create classes `Id`, `SymbolId`, `SetVarId` so that validated strings can be reused for constructing `App`, `SortApp`, etc. https://github.com/runtimeverification/pyk/pull/274
* [x] Make KORE text output more concise by saving on whitespace https://github.com/runtimeverification/pyk/pull/278
* [x] Create method `Kore.write` that enables writing KORE text to a stream directly https://github.com/runtimeverification/pyk/pull/278
* [x] Make `encode_kore_str` more performant https://github.com/runtimeverification/pyk/pull/281

**Comment by ehildenb** [comment]
It would be good to re-profile KEVM once these changes are in.
