### ISSUE TITLE
Refactor `KCFG` printer methods

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#291]
Move methods to module `show`:

```
EdgeLike.pretty
pretty_segments
pretty
to_dot
```

Extract abstract class `KCFGShow`:

```python3
class KCFGShow(ABC):
    @abstractmethod
    show(self, cfg: KCFG) -> str:
        ...

    def __call__(self, cfg: KCFG) -> str:
        return self.show(cfg)
```

Make each printing function where it makes sense a subclass of `KCFGShow` (e.g. `KCFGDotShow`, `KCFGPrettyShow`, ...).

**Comment by ehildenb** [comment]
The individual components of `pretty_segments` should be exposed, so that they can be unit-tested: https://github.com/runtimeverification/pyk/pull/302#discussion_r1148509812

**Comment by ehildenb** [comment]
This is largely done, printing of KCFGs and Proofs has seen major overhauls.
