### ISSUE TITLE
`run_process` in pyk/cli_utils.py should default to inheriting the environment

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#3]
Currently, if the user does not supply the `env` parameter to `run_process` (https://github.com/runtimeverification/k/blob/a3b3f34bb6d08179ee5bc7d3489d8f98b0f46bd6/pyk/src/pyk/cli_utils.py#L52), then the pyk library will supply a _blank_ environment.

We should:

- Have it default to the current environment instead.
- Have the user be allowed to specify environment _overrides_, rather than the entire environment. So whatever the user supplies is added to the current environment instead of overriding it. Maybe rename the parameter to `extra_env`.

**Comment by ehildenb** [comment]
So it sounds like we should keep the current behavior and close this?

**Comment by tothtamas28** [comment]
> So it sounds like we should keep the current behavior and close this?

Yes, I think so.
