### ISSUE TITLE
KAtt serailization and deserialization should recurse into attribute values.

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/pyk#35]
1. Change `KAtt.to_dict`, `KAtt.from_dict`
2. We may probably  change the super-type of `KAtt` to `Mapping[str, Union[str, int, KInner]]`
3. We can drop the `_freeze` function in its constructor.

Some cases to test, where attributes are left as dicts are:

1. The sort attribute, where it stores a deserialized KSort instead of a serialized one.
4. The location attribute.
5. (there may be more, e.g. strictness...)

**Comment by ehildenb** [comment]
@nishantjr is this still relevant/a problem? This issue is pretty old, just not sure what was the goal here or if it's changed enough that it's not a problem anymore.
