### ISSUE TITLE
Should `AGProver/AGProof` actually be `AFProver/AFProof`?

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#355]
@h0nzZik we picked `AGProof` from the CTL terminology: https://en.wikipedia.org/wiki/Computation_tree_logic

But `AG` means "all globally", which means that once the property holds, it continues to hold into the future (as far as I can tell). But that's not what our prover is checking, it's just checking that it holds at a specific point in the future, and doesn't care about states after that. I think what we have implemented is closer to `AF`, which is "all finally", meaning on every finite path of execution, there is some state where the target property holds.

Proof classes intorduced here: https://github.com/runtimeverification/pyk/pull/311

**Comment by h0nzZik** [comment]
You are right that AG is incorrect for what we do, we do AF. Imo AG means that the property holds on all paths in all states.

**Comment by h0nzZik** [comment]
But actually, even CTL's AF has different semantics than all-path reachability, since it does not enforce the property on non-terminating executions.

**Comment by ehildenb** [comment]
Maybe instead we should just call it `APRProver` and `APRProof`

**Comment by h0nzZik** [comment]
APRProver sounds good to me. With regards the CTL*, that logic even does not know the concept of termination - only nonterminating runs are considered there. So even the weak future may be imprecise, or at least confusing.

**Comment by h0nzZik** [comment]
Shall I create a PR with the renaming?

**Comment by ehildenb** [comment]
Yes, please do.

**Comment by h0nzZik** [comment]
Closed by https://github.com/runtimeverification/pyk/pull/382.
