### ISSUE TITLE
Crash in `create_split` with some proofs when trying to read proof JSON dict

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/pyk#398]
I get a crash that looks something like:
```
ValueError: Cannot create split node with less than 2 targets: 3d833acf549ed2037177cfe864d8b67afbb6e3fd2d18b5a38301cd127e651411 -> [('3d833acf549ed2037177cfe864d8b67afbb6e3fd2d18b5a38301cd127e651411', CSubst(subst=Subst(_subst=FrozenDict({})), constraints=()))]
```
I think this split node with only one target is created in the proof when two rules apply on the same step but neither requires adding a constraint, e.g.,
```k
configuration <k> a </k>
syntax Step ::= "a" | "b" | "c" | "d"
rule a => b
rule a => c
rule b => d
rule c => d
```

```k
claim <k> a => d </k>
```
and we get an info message like:  
```
pyk.kcfg.explore - Found 2 branches for node LoopsTest.sum_N: 3d833a..651411: ['#Top', '#Top']
```
If we remove the check [here](https://github.com/runtimeverification/pyk/blob/61551a6f89ac2ac2aedc10fa7bdcc2974870082d/src/pyk/kcfg/kcfg.py#L853), and also change [`_print_split_edge`](https://github.com/runtimeverification/pyk/blob/61551a6f89ac2ac2aedc10fa7bdcc2974870082d/src/pyk/kcfg/kcfg.py#L379) to insert at least one line to prevent an array out of bounds in [`print_subgraph`](https://github.com/runtimeverification/pyk/blob/61551a6f89ac2ac2aedc10fa7bdcc2974870082d/src/pyk/kcfg/kcfg.py#L438), it shows a KCFG, but I think it's the correct one, because there actually are 2 branches, but we loop back because adding the empty constraint to a node results it having the same ID after the split.

**Comment by ehildenb** [comment]
Likely https://github.com/runtimeverification/pyk/pull/329 will fix this. I will pick that one up tomorrow to see if it can be made to address this problem.
