### ISSUE TITLE
Proof re-use via rule logs

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#414]
- Log the rules used for each RPC call.
- When a new rule is added, or a rule is modified, or a rule removed, then invalidate all RPC calls that used that rule.
- Re-run just those ones.

**Comment by palinatolmach** [comment]
@ehildenb is it still planned?

**Comment by ehildenb** [comment]
It may be a big performanec win, but we're too far away from being able to do something like this right now.
