### ISSUE TITLE
Error: kbuild directory does not exist in a docker container

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/pyk#456]
The error was encountered when attempting to run `kmir parse` in a docker containter.

# Steps to reproduce:
## build `mir-semantics` image and run kmir in a docker container
```
$ git clone --recurse-submodules git@github.com:runtimeverification/mir-semantics.git
$ docker build . --build-arg K_COMMIT=$(cat ./deps/k_release) --tag mir-semantics:$(cat ./deps/k_release)
$ docker run --name mir-semantics --rm -it -u user --workdir /home/user mir-semantics:$(cat ./deps/k_release) 
```
## install kmir globally (run via poetry shell returns the same problem).
```
poetry build
pip install dist/*.whl
```
## attempting to run `kmir parse`
```
$ kmir parse --definition-dir $(kbuild which llvm) src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir
```
returns `directory does not exist` error
```
Directory does not exist: /home/user/.kbuild/mir-semantics/7afaf5d/target/v5.5.147/llvm
usage: kmir parse [-h] [--definition-dir DEFINITION_DIR]
                  [--input {program,binary,json,kast,kore}]
                  [--output {pretty,program,json,kore,kast,none}]
                  input_file
kmir parse: error: argument --definition-dir: invalid dir_path value: 'src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir
```

Further comments, this error appears too on a Ubuntu machine without docker. However replacing `poetry build` with `make build` solves the problem (not working in docker).

**Comment by geo2a** [comment]
This happens to be a mix-up in `mir-semantics`' build system, fixed by https://github.com/runtimeverification/mir-semantics/pull/151

**Comment by ehildenb** [comment]
@yanliu18 if this is still an issue, please re-open.
