### ISSUE TITLE
Standard kompilation output for kore-rpc-booster

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/pyk#494]
Now that we are introducing the `kore-rpc-booster` , we need to think about the kompilation steps necessary, since the booster relies on the llvm-backend shared library which we need to kompile and the pass to the rpc server. Foundry currently implements a convention whereby `foundry-kompile` produces `out/kompiled` and `out/kompiled-llvm` folders, with the interpreter being placed in `out/kompiled-llvm/interpreter.{so,dylib}` thus, when we call `foundry-prove` we check this location for the interpreter, when running with booster. It would be useful to do something similar in general pyk or have a mechanism for finding the interpreter, so that using the booster is as friction free as possible.

**Comment by tothtamas28** [comment]
For now, I think it's best to decouple server configuration from client code, e.g. the server should be configured from environment variables with a common prefix (e.g. `BOOSTER_LLVM_DIR`), using a config file with a predefined schema (e.g. `booster.toml`), or maybe even command line arguments (but we'll eventually have a lot of those I think).

There of course might be configuration options for which we can come up with reasonable defaults. We can define those later as we observe the clients to converge to best practices.

**Comment by tothtamas28** [comment]
`kore-rpc-booster` supports `--llvm-backend-library` now.
