### ISSUE TITLE
Fix performance bottleneck in APRProver and APRBMCProver

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/pyk#529]
When we use `kevm prove --test Contract.function--break-every-step`, we can see performance degrading over time. We initially make 1 or 2 calls to `APRProver.adance_proof` per second; the longer the proof runs, the longer it takes for each call. After 1000 steps, we only make one call every 20 seconds.

The reason is that the KCFG grows, and writing it to disc takes longer. When using the APRBMCProver, the situation is even worse because we write each KCFG three times to disc.

There are two low-hanging fruits here:

1) Avoid writing the same KCFG to disk multiple times.
2) Instead of writing to disc after every exploration step, we can write every X minutes. Where X has a sensible default and may be configurable by a CLI argument.

I used the following hotfix locally, and I was able to complete a proof in less than 1h that otherwise took more than 20h on my computer:

~~~diff
diff --git a/src/pyk/proof/reachability.py b/src/pyk/proof/reachability.py
index 3b7a783..b731a0d 100644
--- a/src/pyk/proof/reachability.py
+++ b/src/pyk/proof/reachability.py
@@ -4,6 +4,7 @@ import json
 import logging
 from dataclasses import dataclass
 from itertools import chain
+import time
 from typing import TYPE_CHECKING
 
 from pyk.kore.rpc import LogEntry
@@ -481,7 +482,6 @@ class APRProver(Prover):
         iterations = 0
 
         while self.proof.pending:
-            self.proof.write_proof()
 
             if max_iterations is not None and max_iterations <= iterations:
                 _LOGGER.warning(f'Reached iteration bound {self.proof.id}: {max_iterations}')
@@ -520,7 +520,6 @@ class APRProver(Prover):
                 module_name=module_name,
             )
 
-        self.proof.write_proof()
         return self.proof.kcfg
 
     def refute_node(self, node: KCFG.Node) -> RefutationProof | None:
@@ -684,8 +683,12 @@ class APRBMCProver(APRProver):
     ) -> KCFG:
         iterations = 0
 
+        last_snapshot = 0.0
+        SNAPSHOT_PERIOD = 60.0 * 15.0 # Take a snapshot every 15 minutes
         while self.proof.pending:
-            self.proof.write_proof()
+            if time.time() - last_snapshot >= SNAPSHOT_PERIOD:
+                self.proof.write_proof()
+                last_snapshot = time.time()
 
             if max_iterations is not None and max_iterations <= iterations:
                 _LOGGER.warning(f'Reached iteration bound {self.proof.id}: {max_iterations}')
~~~

The hotfix needs cleaning up and adding a CLI argument to make `SNAPSHOT_PERIOD` configurable.

**Comment by ehildenb** [comment]
I wonder if another fix would be to store more granular data from the KCFG on disk? For example, have a `nodes` subdirectory (because `nodes` are probably the largest piece of data), and have the `APRProof` instead write each node to a separate file?

I also know that @tothtamas28 has been working on a data-model for the `Proof` and `KCFG` datastructures, so perhaps he should be consulted about this as well.

**Comment by ehildenb** [comment]
We may consider having a `kcfgs` subdirectory of the `proofs` subdirectory, where we store information related to each independent KCFG, including the `nodes` subdirectory for example. If we store the nodes hash-addressed ot disk, we can just check the Node hash, and if that file no disk already exists, avoid writing it again (that way we save on disk IO).
