### ISSUE TITLE
Running integration tests fails when combining nix and non-nix tooling

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/pyk#545]
`make cov-integration` fails for me on a Linux machine with `K` installed through `kup` and local installation of `/usr/bin/python3`  (version 3.10.6) and ``$HOME/.local/bin/poetry`

To reproduce:
* install `K` using `kup`
* install a local `python3` and `python3-dev` (using `apt`) and `poetry` (using `pip`)
* run `make cov-integration`

Symptom:
An `llvm-kompile` command fails because a header file `x86_64-linux-gnu/python3.10/pyconfig.h` is not found.

Additional information:

* The `nix`-provided `llvm-kompile-clang` (script) is patched correctly to overwrite the `python3`  command with a `nix`-provided one.
* However, the integration test uses the `--python` option of the script to set a different `python3` version, provided by `poetry` with the current library in scope that should be tested

Using `nix develop` fails with a different error  for me:

```
pyk$ nix develop
...
pyk$ make cov-integration
poetry install
Traceback (most recent call last):
  File "$HOME/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
ModuleNotFoundError: No module named 'poetry.console'
make: *** [Makefile:20: poetry-install] Error 1
[error: 2]--pyk$
```
Obviously, `poetry` is not provided to the nix develop shell.

**Comment by tothtamas28** [comment]
@jberthold do you still see this issue?

**Comment by jberthold** [comment]
I can still see the first issue described (attaching 
[the console output here](https://github.com/runtimeverification/pyk/files/13171565/cov-integration-error.log)).
Haven't retried the `nix develop` variant. I seem to remember `poetry` was added to the `nix` derivation.

**Comment by tothtamas28** [comment]
Fixed in https://github.com/runtimeverification/k/pull/3823:

```
$ poetry env use --no-cache $(k-which-python)
```
