### ISSUE TITLE
How should vacuous nodes be represented in KCFG?

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/pyk#581]
With https://github.com/runtimeverification/haskell-backend/pull/3637, `kore-rpc` now returns `#Bottom` for an `#assume(false)` rule.
```
StuckResult(state=State(term=Bottom(sort=SortApp(name='SortGeneratedTopCell', sorts=())), substitution=None, predicate=Bottom(sort=SortApp(name='SortGeneratedTopCell', sorts=()))), depth=670, logs=())
```

The question is, how should we represent these nodes in the KCFG?
Take the example presented in [#1944](https://github.com/runtimeverification/evm-semantics/issues/1944).
Where `vacuous` means simplifying to `#Bottom`.

```solidity
    function atLeastOneIsValidAddress(address alice, address bob)
        internal
        returns (bool)
    {
        if (alice != address(0)) {
            return true;
        } else if (bob != address(0)) {
            return true;
        } else {
            return false;
        }
    }

    function test_assume_return(address alice, address bob) public {
        vm.assume(atLeastOneIsValidAddress(alice, bob));

        assert(true);
    }
```

A few solutions that @tothtamas28 proposed are: 
1. Store `#Bottom` directly.
    Pros: You can represent vacuous states directly with an edge/cover to `#Bottom`.
    Cons: CTerm cannot encode it right now: #13 

2. Store some state leading to `#Bottom`
    Pros: No modification to `CTerm` necessary
    Cons: Requires `vacuous` set. Potentially requires modification to the server.

3. Do not store these branches.
    Cons: part of the proof is not explicitly encoded.

**Comment by ehildenb** [comment]
I think we should do (2), and store a `vacuous` set idrectly in the KCFG, since `vacuous` is something the backend could reasonably compute on its own.

**Comment by anvacaru** [comment]
Implemented in:  https://github.com/runtimeverification/pyk/pull/587.
