### ISSUE TITLE
`kbuild` should put definitions in a local folder by default

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#586]
Currently artifacts built by `kbuild` are placed in a folder structure like this:

```
~/.kbuild
├── hoon-semantics
│   └── d2f5ce0
│       ├── include
│       │   └── hoon-semantics
│       └── target
│           └── v5.6.110-0-gf2f25ce798
│               ├── haskell
│               └── llvm
...
```

The idea is that the `~/.kbuild` folder serves as a user-local repository for kompiled definitions, arranged by source of installation (`d2f5ce0`) and K version (`v5.6.110-0-gf2f25ce798`).

However, for semantics projects, this seems to be more of an inconvenience than a feature. There, `.kbuild` is only used to produce the definitions but they are distributed in some other way. But due to the complex folder structure, the artiacts can only be accessed through `kbuild which`.

So by default `kbuild` just should output targets in a local folder, e.g.:

```
./kdist
└── hoon-semantics
    ├── include
    │   └── hoon-semantics
    ├── haskell
    └── llvm
```

Maybe the repository thing can even be dropped altogether.

**Comment by tothtamas28** [comment]
@geo2a, @virgil-serbanuta, what's your opinion?

**Comment by ehildenb** [comment]
I personally am _always_ in favor of directory local builds, and only if the user does something like `kbuild install ...` does it go to the user-level or system-level.

**Comment by virgil-serbanuta** [comment]
I also like local builds.

I think that it's a good idea to somehow rebuild the semantics when the `k` version changes, so I like having separate builds for each `k` version (although this is not the only way to solve this issue - writing the version in a file and checking it would also work).
