### ISSUE TITLE
[pyk] library cleanups

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#6]
- [ ] `kit.py` executable should be renamed `kit`: https://github.com/runtimeverification/k/pull/2787/files#r942027065
- [ ] `spec_file` should not be a member of `CFGManager`: https://github.com/runtimeverification/k/pull/2787/files#r941726349
- [ ] We're introducing case-split functionality, but not recording that the case-split is complete or not. 
- [ ] Getting weirdness around the unit klabels for K syntactic lists: https://github.com/runtimeverification/k/pull/2787/files#r941233245
~- [ ] Test `BoolMlPredConversionsTest` has missing types, and could be made better by testing they are invertible: https://github.com/runtimeverification/k/pull/2800#discussion_r944197861~
- [ ] `kit.parse_token_rule_syntax` should be merged into `kprint.parse_token` once `kast` supports it. https://github.com/runtimeverification/k/pull/2807
- [ ] Common functionality between `solc-to-k` and `foundry-to-k` in `__main__.py` should be factored out.

**Comment by radumereuta** [comment]
This got duplicated during transfer. See #5
