### ISSUE TITLE
Add multiple verbosity levels to incorporate kompile logs

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/pyk#600]
With how the `kompile` args are generated([see here](https://github.com/runtimeverification/evm-semantics/blob/5cda4c794acc592943f2c6322f11e0744884acc5/kevm-pyk/src/kevm_pyk/kompile.py#L109-L118)), there is no way to pass `--verbose` to kompile to see the logs.

I would plan to make the general `--verbose` arg in pyk countable and add a new log level named `VERBOSE` with a priority in between `INFO` and `DEBUG`. This way:
  - `--verbose`/`-v`/`--debug` would keep logging the same information
  - `-vv` will log additional information captured from `kompile --verbose`

The changes I propose are to:
1. set the `--verbose` argument type to `count` in https://github.com/runtimeverification/pyk/blob/master/src/pyk/cli/args.py#L20
2. define a new constant `VERBOSE:Final = 15` for the verbosity priority.
3. update the[ loglevel() ](https://github.com/runtimeverification/pyk/blob/master/src/pyk/cli/utils.py#L22)function to accomodate new level.
4. add the new level and update the [_loglevel](https://github.com/runtimeverification/evm-semantics/blob/5cda4c794acc592943f2c6322f11e0744884acc5/kevm-pyk/src/kevm_pyk/__main__.py#L1119) in kevm.
5. include the `verbose = _LOGGER.getEffectiveLevel() == VERBOSE` in https://github.com/runtimeverification/evm-semantics/blob/5cda4c794acc592943f2c6322f11e0744884acc5/kevm-pyk/src/kevm_pyk/kompile.py#L109-L118

**Comment by tothtamas28** [comment]
Maybe `--verbose` can just include information from `kompile --verbose`. What do you think?

**Comment by anvacaru** [comment]
That would be easier to implement and would not require changes on the pyk library. I guess either `--verbose` or `--debug` should do then.
