### ISSUE TITLE
Send AC symbols using `\left/right-assoc` in kore-rpc responses

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/pyk#629]
# Proposal
We propose a change to how `kore-rpc` and `kore-rpc-booster` send back terms containing AC symbols, specifically:
* predicates
* maps/sets

At the moment the returned state has a predicate field which is a term of the shape `And ( ... And(p1, p2) ..., pn)`. We propose to instead send back `\right-assoc{And}(p1,...,pn)`. The same would apply to any map/set concat operators. In theory, this change should be completely transparent to pyk, as the specification of kore equates these two forms, however, we would like to confirm with @tothtamas28 or perhaps someone else on the pyk team whether this is indeed the case.

# Motivation

The motivation for this change is the testing harness we are currently setting up for testing conformance to the contract that the old backend and the booster should return the 'same' results for identical requests. Of course, given maps and predicates, this equivalence is likely to be only up to AC for the given symbols. Rather than trying to get both backends to agree exactly syntactically, it would be easier to modify our diffing algorithm to simply assume any `\left/right-assoc` nodes in the AST are AC symbols and do the diffing up to list permutations (this is obviously not an assumption that is in the contract of kore itself and would be specific to the haskell and booster backends)

**Comment by jberthold** [comment]
Related : https://github.com/runtimeverification/pyk/pull/615

**Comment by tothtamas28** [comment]
`\right-assoc{And}(p1,...,pn)` is no longer supported as of https://github.com/runtimeverification/k/pull/3679.
