### ISSUE TITLE
Branch handling improvements

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/pyk#632]
I have observed one problem and one detail with the branch extraction mechanism in `pyk` while working on a recent engagement:

**Problem**: the results of the `extract_branches` function (as used [here](https://github.com/runtimeverification/pyk/blob/a18d76df9419194acf1f9d159d8fa697e0471bd9/src/pyk/kcfg/explore.py#L376)) are not simplified or checked for satisfiability. This means that by using the mechanism we could end up with more complex terms in the path constraint or explore vacuous branches. My experience is that simplifications being applied is essential for tractability of our verification. For this reason, I am currently commenting out the `extract_branches` of KEVM while working with client code. I see two solutions:

1. Let the backend handle the branching fully - this will ensure the simplifications are done
2. Simplify manually in `pyk` (which does mean calling the backend) while checking feasibility

**Detail**: It is not always the case that the path constraints of next states syntactically extend the path constraint of the initial state. For example, if we learn that two symbolic variables are equal, then the backend will perform the substitution. This means that [this check](https://github.com/runtimeverification/pyk/blob/a18d76df9419194acf1f9d159d8fa697e0471bd9/src/pyk/kcfg/explore.py#L419) will not always work (as @lucasmt noticed). I have also [flagged this substitution behaviour](https://github.com/runtimeverification/haskell-backend/issues/3648) to the Haskell backend team so that it can be confirmed that it is desired.

**Comment by ehildenb** [comment]
A simple solution would be to check the feasibility of each branch that is extracted with `extract_branches` heuristic by passing it through the `simplify` endpoint. Then if any of the branches go to `#Bottom`, we discard that branch.

If we are left with just a single branch, we could can skip the extract branches logic and instead go through to the execute case. Something like this: https://github.com/runtimeverification/pyk/blob/e16401475cf16636e48cbd4e41b9fc85d2b614ef/src/pyk/kcfg/explore.py#L376, replaced with:

```
        if not kcfg.splits(target_id=node.id):
            branches = [self.cterm_simplify(branch) for branch in self.kcfg_semantics.extract_branches(node.cterm)]
            branches = [branch for branch in branches if not branch._is_bottom]
            if len(branches) > 1:
                kcfg.split_on_constraints(node.id, branches)
                _LOGGER.info(
                    f'Found {len(branches)} branches using heuristic for node {node.id}: {shorten_hashes(node.id)}: {[self.kprint.pretty_print(bc) for bc in branches]}'
                )
                return
```

**Comment by PetarMax** [comment]
Yes, this would work. The thing is that the returned branches (constraints, really) should be simplified with respect to both all of the simplifications we have as well as the current path constraint, so we need the correct way of doing that? I will explore...

**Comment by ehildenb** [comment]
You can probably use the routine `APRProof.path_constraints` to help here: https://github.com/runtimeverification/pyk/blob/e87862c070793908b2e7983222bddd71f5c0bb69/src/pyk/proof/reachability.py#L208
