### ISSUE TITLE
Validate flags used in `kbuild.toml`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/pyk#771]
In https://github.com/runtimeverification/mir-semantics/pull/291, I noticed that specifying an unsupported flag in `kbuild.toml` will silently succeed, rather than giving any kind of warning or error that the flag isn't actually being used.

We should check for such cases and report them at build time.

**Comment by gtrepta** [comment]
I see some duplication between these two related parameter lists. Could we instead have `kbuild` rely on `kompile` to define what flags are available and validate them?

https://github.com/runtimeverification/pyk/blob/f9a2da504dd4d4b366973185b7d66f07b00bba12/src/pyk/ktool/kompile.py#L320-L331

https://github.com/runtimeverification/pyk/blob/f9a2da504dd4d4b366973185b7d66f07b00bba12/src/pyk/kbuild/project.py#L60-L82

**Comment by gtrepta** [comment]
I just drafted a PR with my proposed solution #792
