### ISSUE TITLE
Add `type-inference-mode` flag to `kbuild`

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/pyk#788]
#767 added support for `type-inference-mode` flag to kompile, however `kbuild` [does not process this flag](https://github.com/runtimeverification/pyk/blob/master/src/pyk/kbuild/project.py#L111-L130).

Adding this flag would allow [mir-semantics PR 291](https://github.com/runtimeverification/mir-semantics/pull/291) to progress

**Comment by tothtamas28** [comment]
Fixed in #792
