### ISSUE TITLE
Set up data layer for K-REPL

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#79]
K-REPL will use a relational database on the backend to store symbolic execution graphs, consisting of a potentially large number of complex KORE patterns.

Related technologies include the following.
* [SQLite](https://www.sqlite.org/), in particular [`sqlite3`](https://docs.python.org/3/library/sqlite3.html) from the standard library for development, testing and local CLI use. In-memory usage is an option.
* [PostgreSQL](https://www.postgresql.org/) for production web use.
* [SQLAlchemy](https://www.sqlalchemy.org/) to abstract over database driver, schema, and queries, and potentially use ORM.
* [Alembic](https://alembic.sqlalchemy.org/) for handling schema evolution (only an issue once in production).

**Comment by ehildenb** [comment]
@tothtamas28 is this still relevant?

**Comment by tothtamas28** [comment]
> is this still relevant?

We'll probably use these technologies once we need a database for storing proofs. Nevertheless, the issue itself can be closed.
