### ISSUE TITLE
Add support for missing HB flags

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/pyk#816]
We should add support for missing Haskell Backend CLI options:
- `--no-post-exec-simplify` ([src](https://github.com/runtimeverification/hs-backend-booster/blob/2d2dd7f5572f574175b20d58f4081c947b5c929d/tools/booster/Server.hs#L289))
- `--interim-simplification N` ([src](https://github.com/runtimeverification/hs-backend-booster/blob/2d2dd7f5572f574175b20d58f4081c947b5c929d/tools/booster/Server.hs#L267C29-L267C29))

**Comment by palinatolmach** [comment]
@geo2a could you check if I missed any options? ty!

**Comment by geo2a** [comment]
@palinatolmach looks good to me!
