### ISSUE TITLE
ability to omit the initialization of cli arguments to defaults during inherited initialization

### ISSUE THREAD

**Issue by ovatman** [runtimeverification/pyk#906]
When working on tomlization of `kontrol` arguments we needed to remove the default initialization of argument variables. This is required because we would like to override the argument values coming from an input toml with the values from cli which. Default value initialization causes the non specified values from the cli to override specified values from the toml.

However, there are some arguments which are inherited from `pyk` to which we can not disable the default value initialization from `kontrol`. It is required to disable such an initialization optionally or when inherited.

**Comment by tothtamas28** [comment]
Right now `cli` provides complete `ArgumentParser` instances, e.g.: https://github.com/runtimeverification/pyk/blob/e21a9ddd4e915b0ed436a8d7c1477db820f1a768/src/pyk/cli/args.py#L16

with arguments like: https://github.com/runtimeverification/pyk/blob/e21a9ddd4e915b0ed436a8d7c1477db820f1a768/src/pyk/cli/args.py#L20

One solution for the issue would be to model the command line arguments, and let the user assemble the parsers themself.

A bare bones example to illustrate the idea:

```python3
cli_arg = (
    ('--verbose', '-v'),
    {
        'default': False,
        'action': 'store_true',
        'help': 'Verbose output.',
    },
)
...
args, kwargs = cli_arg
parser.add_argument(*args, **kwargs)
```

This should of course be properly modeled with classes that represent the arguments (or groups of them) and enable constructing / enriching argument parsers. Then users had the option to exclude an argument, or modify some of their parts (the `default` in this case).

This would also make it easier to migrate to another argument parser library.

**Comment by ehildenb** [comment]
See https://github.com/runtimeverification/pyk/issues/885

**Comment by yale-vinson** [comment]
@ovatman What is blocking this one? I want to reference it here so that we know when we can come back to work on this one.
