### ISSUE TITLE
KAst.from_dict is no longer concrete method

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#97]
Due to https://github.com/runtimeverification/pyk/pull/96, we have that `KAst.from_dict` is now virtual.

It's debatable to me whether it needs to be non-virtual in any cases, but this is here to track that. If people need it (they don't know whether the file they are reading is `KInner` or `KOuter`, for example), then they can comment here and let us know.

**Comment by tothtamas28** [comment]
The function signature

```python3
def from_dict(cls: Type[T], d: Dict[str, Any]) -> T
```

with `T = TypeVar('T', bound='KAst')` is not type safe. The simplest way to fix this is by implementing `KAst.from_dict` in the reasonable way. Alternatives are duplicating code in `KInner` and `KOuter`, or coming up with a more complicated and weaker type hint.

A use case for calling `KAst.from_dict`: converting JSON KAST to pretty format.
